import { useEffect, useState } from 'react';
import { getSiteMap } from '@/services/authService';

const SitemapXml = () => {
  const [xmlContent, setXmlContent] = useState<string>('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const meta = document.createElement('meta');
    meta.httpEquiv = 'Content-Type';
    meta.content = 'application/xml; charset=utf-8';
    document.head.appendChild(meta);

    const fetchSitemap = async () => {
      try {
        const response = await getSiteMap();
        if (response.ok && response.headers.get('content-type')?.includes('xml')) {
          const xml = await response.text();
          setXmlContent(xml);
        } else {
          generateFallbackSitemap();
        }
      } catch (error) {
        console.error('Error fetching sitemap:', error);
        generateFallbackSitemap();
      } finally {
        setLoading(false);
      }
    };

    fetchSitemap();

    return () => {
      document.head.removeChild(meta);
    };
  }, []);

  const generateFallbackSitemap = () => {
    const baseUrl = window.location.origin;
    const currentDate = new Date().toISOString().split('T')[0];

    const urls: { path: string; changefreq: string; priority: string }[] = [
      { path: '/', changefreq: 'daily', priority: '1.0' },
      { path: '/about', changefreq: 'monthly', priority: '0.8' },
      { path: '/articles', changefreq: 'weekly', priority: '0.7' },
      { path: '/contact', changefreq: 'monthly', priority: '0.6' },
      { path: '/login', changefreq: 'monthly', priority: '0.5' },
      { path: '/signup', changefreq: 'monthly', priority: '0.5' },
      { path: '/signup/parent', changefreq: 'monthly', priority: '0.5' },
      { path: '/signup/doctor', changefreq: 'monthly', priority: '0.5' },
      { path: '/signup/clinic-admin', changefreq: 'monthly', priority: '0.5' },
      { path: '/forgot-password', changefreq: 'monthly', priority: '0.4' },
      { path: '/privacy', changefreq: 'yearly', priority: '0.3' },
      { path: '/terms', changefreq: 'yearly', priority: '0.3' },
      { path: '/sitemap', changefreq: 'monthly', priority: '0.4' },
      { path: '/sitemap.xml', changefreq: 'weekly', priority: '0.5' },
    ];

    const urlEntries = urls
      .map(
        (u) => `    <url>
        <loc>${baseUrl}${u.path === '/' ? '/' : u.path}</loc>
        <lastmod>${currentDate}</lastmod>
        <changefreq>${u.changefreq}</changefreq>
        <priority>${u.priority}</priority>
    </url>`
      )
      .join('\n');

    const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Kittyp Frontend Fallback -->
<!-- Last Updated: ${currentDate} -->
<!-- Total URLs: ${urls.length} -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
        http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">

${urlEntries}

</urlset>`;

    setXmlContent(sitemap);
  };

  if (loading) {
    return <div>Loading sitemap...</div>;
  }

  return (
    <pre style={{ whiteSpace: 'pre-wrap', fontFamily: 'monospace' }}>
      {xmlContent}
    </pre>
  );
};

export default SitemapXml;
